--- 
HOST_URL: "something.atlassian.net"
USER_EMAIL: "email address for the Atlassian account you're using to create the token (user.name@company.com)"
API_TOKEN: "token ID generated at https://id.atlassian.com/manage/api-tokens"
INCLUDE_ATTACHMENTS: "include attachments? this will make the backup size bigger - true / false"
DOWNLOAD_LOCALLY: "download the backup file to backups folder? true / false"
UPLOAD_TO_S3:
    AWS_ENDPOINT_URL: "amazon S3 endpoints https://docs.aws.amazon.com/general/latest/gr/s3.html"
    AWS_REGION: "amazon S3 region"
    S3_BUCKET: "S3 bucket name (empty value will skip this step)"
    S3_DIR: "S3 directory for upload (example Atlassian/)"
    AWS_ACCESS_KEY: "not mandatory if already set on the machine with AWS CLI"
    AWS_SECRET_KEY: "not mandatory if already set on the machine with AWS CLI"
    AWS_IS_SECURE: True